valouxServices.service('masterDataService',['$http', '$q', '$rootScope', function($http, $q, $rootScope){

    return {
        relationshipCategories : function () { //Array of relationships
            var status_categories = [
                    {'value': 1 , 'name': 'Divorced'},
                    {'value': 2, 'name': 'Engaged'},
                    {'value': 3, 'name': 'In a civil union'},
                    {'value': 4, 'name': 'In a domestic partnership'},
                    {'value': 5, 'name': 'In a relationship'},
                    {'value': 6, 'name': 'In an open relationship'},
                    {'value': 7, 'name': 'Its complicated'},
                    {'value': 8, 'name': 'Married'},
                    {'value': 9, 'name': 'Not specified'},
                    {'value': 10, 'name': 'Separated'},
                    {'value': 11, 'name': 'Single'},
                    {'value': 12, 'name': 'Widowed'}
                ];
            return status_categories;
        },
        
        incomeRange_categories : function () { //Array of income Range
            var incomeRange_categories = [
                    {'value': 1, 'name': '0-10k'},
                    {'value': 2, 'name': '10-30K'},
                    {'value': 3, 'name': '30K-50K'},
                    {'value': 4, 'name': '50K-80K'},
                    {'value': 5, 'name': '80K-100K'},
                    {'value': 6, 'name': '100K-150K'},
                    {'value': 7, 'name': '150K-500K'},
                    {'value': 8, 'name': '500K-1M'},
                    {'value': 9, 'name': '1M+'}
                    ];
            return incomeRange_categories;
        },
        allDesignType : function () { //Array of design Type
            var allDesignType = [
                    {'value': 1, 'name': 'Designer'},
                    {'value': 2, 'name': 'Artistic'},
                    {'value': 3, 'name': 'Handmade'},
                    {'value': 4, 'name': 'Custom Design'},
                    {'value': 5, 'name': 'Manufactured'},
                    {'value': 6, 'name': 'Limited Edition'},
                    {'value': 7, 'name': 'Fashion'},
                    {'value': 8, 'name': 'Replica'},
                    {'value': 9, 'name': 'Signed'},
                    ];
            return allDesignType;
        },
        jewelryPurchases : function () { //Array of jewelry Purchases for consumer form
            var jewelryPurchasesType = [ 
                    {'value': 1, 'name': 'Multiple times a year'},
                    {'value': 2, 'name': 'Once or twice a year'},
                    {'value': 3, 'name': 'Rarely'}
                    ];
            return jewelryPurchasesType;
        },
        jewelryInsurances : function () { //Array of jewelry Insurances for consumer form
            var jewelryInsuranceType = [ 
                    {'value': 30, 'name': "Homeowner's"},
                    {'value': 31, 'name': "Jewelry Specific"},
                    {'value': 32, 'name': 'No Insurance'},
                    {'value': 33, 'name': 'Renters'},
                    {'value': 34, 'name': "Supplemental through Homeowner's"},
                    ];
            return jewelryInsuranceType;
        },
        jewelryService : function () { //Array of jewelry Service for consumer form
            var jewelryServiceType = [ 
                    {'value': 60, 'name': "Every 3-5 years"},
                    {'value': 61, 'name': "Never"},
                    {'value': 62, 'name': 'Once a year'},
                    
                    ];
            return jewelryServiceType;
        },
        jewelryDocumentation : function () { //Array of jewelry Documentation for consumer form
            var jewelryDocumentationType = [  
                    {'value': 90, 'name': "Stored Electronically"},
                    {'value': 91, 'name': "Don't have"},
                    {'value': 92, 'name': "Filed (paper)"},
                    ];
            return jewelryDocumentationType;
        },
        metals : function () { //Array of metals for consumer form
            var metals = [ 
                    {'value': 1, 'name': "Copper"},
                    {'value': 2, 'name': "Gold (Rose)"},
                    {'value': 3, 'name': "Gold (White)"},
                    {'value': 4, 'name': "Gold (Yellow)"},
                    {'value': 5, 'name': "Palladium"},
                    {'value': 6, 'name': "Platinum"},
                    {'value': 7, 'name': "Silver"},
                    {'value': 8, 'name': "Other"},
                    ];
            return metals;
        },
        gemstones : function () { //Array of gemstones for consumer form
            var gemstonesType = [ 
                    {'value': 30, 'name': "30 Ruby"},
                    {'value': 31, 'name': "Emerald"},
                    {'value': 32, 'name': "Sapphire"},
                    {'value': 33, 'name': "Topaz"},
                    {'value': 34, 'name': "Other"},
                    ];
            return gemstonesType;
        },
        diamonds : function () { //Array of diamonds for consumer form
            var diamondsType = [  
                    {'value': 60, 'name': "60 Round"},
                    {'value': 61, 'name': "Designer Cut"},
                    {'value': 62, 'name': "Emerald"},
                    {'value': 63, 'name': "Oval"},
                    {'value': 64, 'name': "Princess"},
                    {'value': 65, 'name': "Other"},
                    ];
            return diamondsType;
        },
        month : function () { //Array of months
            var month = new Array();
            month[0] = "January";
            month[1] = "February";
            month[2] = "March";
            month[3] = "April";
            month[4] = "May";
            month[5] = "June";
            month[6] = "July";
            month[7] = "August";
            month[8] = "September";
            month[9] = "October";
            month[10] = "November";
            month[11] = "December";
            return month;
        },
        certificateType : function () { //Array of diamonds for consumer form
            var certificateType = [
                    {'value': 3, 'name': "GIA"},
                    {'value': 1, 'name': "AGS"},
                    {'value': 2, 'name': "EGL"},
                    ];
            return certificateType;
        },
        clarityType : function () { //FL, IF, VVS1, VVS2, VS1, VS2, SI1, SI2, I1, I2, I3
            var clarityType = [  
                    {'value': 1, 'name': "Flawless",'scode':'FL'},
                    {'value': 2, 'name': "Internally Flawless",'scode':'IF'},
                    {'value': 3, 'name': "VVS1",'scode':'VVS1'},
                    {'value': 4, 'name': "VVS2",'scode':'VVS2'},
                    {'value': 5, 'name': "VS1",'scode':'VS1'},
                    {'value': 6, 'name': "VS2",'scode':'VS2'},
                    {'value': 7, 'name': "Si1",'scode':'SI1'},
                    {'value': 8, 'name': "Si2",'scode':'SI2'},
                    {'value': 9, 'name': "Si3",'scode':'SI3'},
                    {'value': 10, 'name': "I1",'scode':'I1'},
                    {'value': 11, 'name': "I2",'scode':'I2'},
                    {'value': 12, 'name': "I3",'scode':'I3'},
                    {'value': 13, 'name': "Opaque",'scode':'I3'}                    
                    ];
            return clarityType;
        },
        diamondColor : function () { //Array of diamonds for consumer form
            var diamondColor = [ 
                    {'value': 1, 'name': "D"},
                    {'value': 2, 'name': "E"},
                    {'value': 3, 'name': "F"},
                    {'value': 4, 'name': "G"},
                    {'value': 5, 'name': "H"},
                    {'value': 6, 'name': "I"},
                    {'value': 7, 'name': "J"},
                    {'value': 8, 'name': "K"},
                    {'value': 9, 'name': "L"},
                    {'value': 10, 'name': "M"},
                    {'value': 11, 'name': "N"},
                    {'value': 12, 'name': "O"},
                    {'value': 13, 'name': "P"},
                    {'value': 14, 'name': "Q"},
                    {'value': 15, 'name': "R"},
                    {'value': 16, 'name': "S"},
                    {'value': 17, 'name': "T"},
                    {'value': 18, 'name': "U"},
                    {'value': 19, 'name': "V"},
                    {'value': 20, 'name': "W"},
                    {'value': 21, 'name': "X"},
                    {'value': 22, 'name': "Y"},
                    {'value': 23, 'name': "Z"},
                    ];
            return diamondColor;
        },
        qualityType : function () { //Array of Polish, Symmetry and Cut- EX, VG, G, F, P
            var qualityType = [  
                    {'value': 1, 'name': "Excellent" ,'scode':'EX'},
                    {'value': 2, 'name': "Very Good",'scode':'VG'},
                    {'value': 3, 'name': "Good",'scode':'G'},
                    {'value': 4, 'name': "Fair",'scode':'F'},
                    {'value': 5, 'name': "Poor",'scode':'P'}                
                    ];
            return qualityType;
        },
        diamondCutlet : function () { //Culet- NON, VSM, SML, MED, LGE, VLG
            var diamondCutlet = [  
                    {'value': 1, 'name': "Very Small",'scode':'VSM'},
                    {'value': 2, 'name': "Small",'scode':'SML'},
                    {'value': 3, 'name': "Medium",'scode':'MED'},
                    {'value': 4, 'name': "Slightly Large",'scode':'SLG'},
                    {'value': 5, 'name': "Large",'scode':'LGE'},   
                    {'value': 6, 'name': "Very Large",'scode':'VLG'},   
                    {'value': 7, 'name': "Extremely Large",'scode':'ELG'},
                    {'value': 8, 'name': "NON",'scode':'NON'} 
                    ];
            return diamondCutlet;
        },
        fancyColor : function () { //Array of diamonds fancy Color Blue, Yellow, White, Orange, Green and Re //  and Re
            var fancyColor = [  
                    {'value': 1, 'name': "Yellow"},
                    {'value': 2, 'name': "Blue"},
                    {'value': 3, 'name': "Green"},
                    {'value': 4, 'name': "Orange"},
                    {'value': 5, 'name': "Black"},   
                    {'value': 6, 'name': "Brown"},   
                    {'value': 7, 'name': "Grey"},
                    {'value': 8, 'name': "Pink"},
                    {'value': 9, 'name': "White"},
                    {'value': 10, 'name': "Red"}
                    ];
            return fancyColor;
        },
        fluorescence : function () { //Fluorescence Intensity- NON, FNT, MED, STG, VST
            var fluorescence = [ 
                    {'value': 1, 'name': "None",'scode':'NON'},
                    {'value': 2, 'name': "Faint",'scode':'FNT'},
                    {'value': 3, 'name': "Medium",'scode':'MED'},
                    {'value': 4, 'name': "Strong",'scode':'STG'},
                    {'value': 5, 'name': "Very Strong",'scode':'VST'} 
                    ];
            return fluorescence;
        },
        
        girdleThickness : function () { //Girdle Condition- Faceted, Polished, Bruted, Lasered and Not Applicable
            var girdleThickness = [  
                    {'value': 1, 'name': "Rough",'scode':'Rough'},
                    {'value': 2, 'name': "Polished",'scode':'Polished'},
                    {'value': 3, 'name': "Faceted",'scode':'Faceted'},
                    {'value': 4, 'name': "Wavy",'scode':'Wavy'},
                    {'value': 5, 'name': "Bruted",'scode':'Bruted'},
                    {'value': 6, 'name': "Lasered",'scode':'Lasered'},
                    {'value': 7, 'name': "Not Applicable",'scode':'Not Applicable'},
                    ];
            return girdleThickness;
        },
        secondaryHue : function () { //Array of diamonds for consumer form
            var secondaryHue = [  
                    {'value': 1, 'name': "Yellowish"},
                    {'value': 2, 'name': "Blueish"},
                    {'value': 3, 'name': "Greenish"},
                    {'value': 4, 'name': "Orangeish"},
                    {'value': 5, 'name': "Brownish"},   
                    {'value': 6, 'name': "Greyish"},   
                    {'value': 7, 'name': "Pinkish"}
                    ];
            return secondaryHue;
        },
        thickness : function () { //Girdle Thickness- NON, VTH, THN, MED, STK, THK, ETK
            var thickness = [  
                    {'value': 1, 'name': "Extremely Thick",'scode':'ETK'},
                    {'value': 2, 'name': "Very Thick",'scode':'VTK'},
                    {'value': 3, 'name': "Thick",'scode':'THK'},
                    {'value': 4, 'name': "Slightly Thick",'scode':'STK'},
                    {'value': 5, 'name': "Medium",'scode':'MED'},   
                    {'value': 6, 'name': "Slightly Thin",'scode':'STH'},   
                    {'value': 7, 'name': "Thin",'scode':'THN'},
                    {'value': 8, 'name': "Very Thin",'scode':'VTH'},
                    {'value': 9, 'name': "Extremely Thin",'scode':'ETH'},
                    {'value': 10, 'name': "NON",'scode':'NON'},
                    ];
            return thickness;
        },
        weightMeasure : function () { //weightMeasure 
            var WeightMeasure = [ 
                    {'value': 1, 'name': "Actual"},
                    {'value': 2, 'name': "Estimated"}
                    ];
            return WeightMeasure;
        },
        componentShape : function () { //Array of componentShape 1-diamond,2-gemstone,3-pearl,4-metal
            var componentShape = [  
                    {'value': 1, 'name': "Round",'componentType':1, 'img':'diamond-round.png','shapeType':'round'},
                    {'value': 2, 'name': "Princess",'componentType':1, 'img':'diamond-princess-cut.png','shapeType':'other'},
                    {'value': 3, 'name': "Emerald",'componentType':1, 'img':'diamond-emerald.png','shapeType':'other'},
                    {'value': 4, 'name': "Asscher",'componentType':1, 'img':'diamond-asscher.png','shapeType':'other'},
                    {'value': 5, 'name': "Cushion",'componentType':1, 'img':'diamond-cushion.png','shapeType':'other'},
                    {'value': 6, 'name': "Marquise",'componentType':1, 'img':'diamond-marquise.png','shapeType':'other'},
                    {'value': 7, 'name': "Radiant",'componentType':1, 'img':'diamond-radiant.png','shapeType':'other'},
                    {'value': 8, 'name': "Oval",'componentType':1, 'img':'diamond-oval.png','shapeType':'other'},
                    {'value': 9, 'name': "Pear",'componentType':1, 'img':'diamond-pear.png','shapeType':'other'},
                    {'value': 10, 'name': "Heart",'componentType':1, 'img':'diamond-heart.png','shapeType':'other'},
                    {'value': 11, 'name': "Straight Baguette",'componentType':1, 'img':'diamond-straight-baguette.png','shapeType':'other'},
                    {'value': 12, 'name': "Trillion",'componentType':1, 'img':'diamond-trillion.png','shapeType':'other'},
                    {'value': 13, 'name': "Round",'componentType':2, 'img':'diamond-round.png','shapeType':'other'},
                    {'value': 14, 'name': "Antique",'componentType':2, 'img':'diamond-antique-cushion.png','shapeType':'other'},
                    {'value': 15, 'name': "Emerald",'componentType':2, 'img':'diamond-emerald.png','shapeType':'other'},
                    {'value': 16, 'name': "Heart",'componentType':2, 'img':'diamond-heart.png','shapeType':'other'},
                    {'value': 17, 'name': "Square",'componentType':2, 'img':'diamond-square.png','shapeType':'other'},
                    {'value': 18, 'name': "Straight Baguette",'componentType':2, 'img':'diamond-straight-baguette.png','shapeType':'other'},
                    {'value': 19, 'name': "Radiant",'componentType':2, 'img':'diamond-radiant.png','shapeType':'other'},
                    {'value': 20, 'name': "Trillion",'componentType':2, 'img':'diamond-trillion.png','shapeType':'other'},
                    {'value': 21, 'name': "Pear",'componentType':2, 'img':'diamond-pear.png','shapeType':'other'},
                    {'value': 22, 'name': "Round",'componentType':3, 'img':'pearl-round.png','shapeType':'other'},
                    {'value': 23, 'name': "Oval",'componentType':3, 'img':'pearl-oval.png','shapeType':'other'},
                    {'value': 24, 'name': "Button",'componentType':3, 'img':'pearl-button.png','shapeType':'other'},
                    {'value': 25, 'name': "Drop",'componentType':3, 'img':'pearl-drop.png','shapeType':'other'},
                    {'value': 26, 'name': "Semi-Baroque",'componentType':3, 'img':'pearl-semi-baroque.png','shapeType':'other'},
                    {'value': 27, 'name': "Baroque",'componentType':3, 'img':'pearl-baroque.png','shapeType':'other'},
                    {'value': 28, 'name': "Rice",'componentType':3, 'img':'pearl-rice.png','shapeType':'other'}
                    
                    //                    {'value': 8, 'name': "Tapered Baguette",'componentType':1, 'img':'diamond-cushion.png','shapeType':'other'},
                    //                    {'value': 8, 'name': "Tapered Baguette",'componentType':2, 'img':'diamond-cushion.png','shapeType':'other'},
                    //                    {'value': 8, 'name': "Near Round",'componentType':3, 'img':'diamond-pear.png','shapeType':'other'},
                    
                    ];
            return componentShape;
        },
        
        diamondShapes : function () { //Array of componentShape 1-diamond,2-gemstone,3-pearl,4-metal
            var diamondShapes = [{"value":1,"name":"Briolette (13)","scode":"B","shapeType":"other"},
{"value":2,"name":"Bat Mixed Cut (R68)","scode":"BAT","shapeType":"other"},
{"value":3,"name":"Bent Top Cut-Cornered Rectangular Step Cut (E67)","scode":"BCRSC","shapeType":"other"},
{"value":4,"name":"Bird Modified Brilliant (R89)","scode":"BIRD","shapeType":"other"},
{"value":5,"name":"Boat Novelty Cut (R11)","scode":"BOAT","shapeType":"other"},
{"value":6,"name":"Blocked Round","scode":"BR","shapeType":"other"},
{"value":7,"name":"Bent Top Rectangular Step Cut (E01)","scode":"BRSC","shapeType":"other"},
{"value":8,"name":"Buff Top Round Mixed Cut (A70)","scode":"BRX","shapeType":"other"},
{"value":9,"name":"Bent Top Square Step Cut (G46)","scode":"BSSC","shapeType":"other"},
{"value":10,"name":"Bull Step Cut (OLD)","scode":"BULL","shapeType":"other"},
{"value":11,"name":"Butterfly Modified Brilliant (R01)","scode":"BUT","shapeType":"other"},
{"value":12,"name":"Cushion Brilliant (4M - F04)","scode":"CB","shapeType":"other"},
{"value":13,"name":"Cut-Cornered Rectangular Rose Cut (E86)","scode":"CCRRC","shapeType":"other"},
{"value":14,"name":"Circular Brilliant (A113)","scode":"CIRC","shapeType":"round"},
{"value":15,"name":"Clover Modified Brilliant (R69)","scode":"CLVR","shapeType":"other"},
{"value":16,"name":"Cushion Modified Brilliant","scode":"CMB","shapeType":"other"},
{"value":17,"name":"Cushion Novelty Cut (F29)","scode":"CNC","shapeType":"other"},
{"value":18,"name":"Cushion Portrait Cut (F19)","scode":"CPC","shapeType":"other"},
{"value":19,"name":"Cushion Rose Cut (F21)","scode":"CRC","shapeType":"other"},
{"value":20,"name":"Cut-Cornered Rectangular Modified Brilliant (E07)","scode":"CRMB","shapeType":"other"},
{"value":21,"name":"Cut-Cornered Rectangular Novelty Cut (E15)","scode":"CRNC","shapeType":"other"},
{"value":22,"name":"Modified Cross Brilliant (R13)","scode":"CROSS","shapeType":"other"},
{"value":23,"name":"Cut-Cornered Rectangular Portrait Cut (E22)","scode":"CRPC","shapeType":"other"},
{"value":24,"name":"Cut-Cornered Rectangular Rose Cut (E69)","scode":"CRRC","shapeType":"other"},
{"value":25,"name":"Cut-Cornered Rectangular Step Cut (E42)","scode":"CRSC","shapeType":"other"},
{"value":26,"name":"Cross Modified Brilliant (OLD)","scode":"CRSS","shapeType":"other"},
{"value":27,"name":"Cut-Cornered Rectangular Mixed Cut (E16)","scode":"CRX","shapeType":"other"},
{"value":28,"name":"Cushion Step Cut (F13)","scode":"CSC","shapeType":"other"},
{"value":29,"name":"Cut-Cornered Square Modified Brilliant (G105)","scode":"CSMB","shapeType":"other"},
{"value":30,"name":"Cut-Cornered Square Portrait Cut (G55)","scode":"CSPC","shapeType":"other"},
{"value":31,"name":"Cut-Cornered Square Step Cut (G06)","scode":"CSSC","shapeType":"other"},
{"value":32,"name":"Cut-Cornered Square Mixed Cut (G100)","scode":"CSX","shapeType":"other"},
{"value":33,"name":"Cut-Cornered Trapezoid Modified Brilliant (T06)","scode":"CTPMB","shapeType":"other"},
{"value":34,"name":"Cut-Cornered Trapezoid Step Cut (T02)","scode":"CTPSC","shapeType":"other"},
{"value":35,"name":"Cut-Cornered Trapezoid Mixed Cut (T38)","scode":"CTPX","shapeType":"other"},
{"value":36,"name":"Cut-Cornered Triangular Modified Brilliant (I13)","scode":"CTRMB","shapeType":"other"},
{"value":37,"name":"Cut-Cornered Triangular Step Cut (I16)","scode":"CTRSC","shapeType":"other"},
{"value":38,"name":"Cut-Cornered Triangular Mixed Cut (I14)","scode":"CTRX","shapeType":"other"},
{"value":39,"name":"Cushion Mixed Cut (F10)","scode":"CX","shapeType":"other"},
{"value":40,"name":"Decagonal Brilliant (L15)","scode":"DB","shapeType":"round"},
{"value":41,"name":"Dolphin Step Cut (R20)","scode":"DLPN","shapeType":"other"},
{"value":42,"name":"Dolphin Double Rose Cut (R59)","scode":"DLPNDR","shapeType":"other"},
{"value":43,"name":"Decagonal Modified Brilliant (L13)","scode":"DMB","shapeType":"round"},
{"value":44,"name":"Eagle Brilliant (R26)","scode":"EAGLE","shapeType":"other"},
{"value":45,"name":"Elephant Step Cut (R28)","scode":"ELPHT","shapeType":"other"},
{"value":46,"name":"Emerald Cut (3 Step, E21)","scode":"EM","shapeType":"other"},
{"value":47,"name":"Faceted Bead (U01)","scode":"FBD","shapeType":"other"},
{"value":48,"name":"Fish Modified Brilliant (R08)","scode":"FISH","shapeType":"other"},
{"value":49,"name":"Flame Step Cut (R16)","scode":"FLM","shapeType":"other"},
{"value":50,"name":"Flame Modified Brilliant (R72)","scode":"FLMMB","shapeType":"other"},
{"value":51,"name":"Flower Brilliant (R38)","scode":"FLWR","shapeType":"other"},
{"value":52,"name":"Gun Step Cut (R87)","scode":"GUN","shapeType":"other"},
{"value":53,"name":"Heart Brilliant (3M/B - H01)","scode":"HB","shapeType":"other"},
{"value":54,"name":"Heart Double Rose Cut (H34)","scode":"HDRC","shapeType":"other"},
{"value":55,"name":"Heart Modified Brilliant (H53)","scode":"HMB","shapeType":"other"},
{"value":56,"name":"Half-Moon Mixed Cut (P02)","scode":"HMN","shapeType":"other"},
{"value":57,"name":"Heart Novelty Cut (H32)","scode":"HNC","shapeType":"other"},
{"value":58,"name":"Heart Portrait Cut (H31)","scode":"HPC","shapeType":"other"},
{"value":59,"name":"Heart Rose Cut (H35)","scode":"HRC","shapeType":"other"},
{"value":60,"name":"Horse Modified Brilliant (R10)","scode":"HRSE","shapeType":"other"},
{"value":61,"name":"Heart Step Cut (H29)","scode":"HSC","shapeType":"other"},
{"value":62,"name":"Heart Mixed Cut (H58)","scode":"HX","shapeType":"other"},
{"value":63,"name":"Hexagonal Brilliant (K01)","scode":"HXB","shapeType":"round"},
{"value":64,"name":"Hexoctahedral Cut","scode":"HXC","shapeType":"round"},
{"value":65,"name":"Hexagonal Modified Brilliant (K02)","scode":"HXMB","shapeType":"round"},
{"value":66,"name":"Hexagonal Step Cut (K05)","scode":"HXSC","shapeType":"round"},
{"value":67,"name":"Hexagonal Mixed Cut (K12)","scode":"HXX","shapeType":"round"},
{"value":68,"name":"Kite Brilliant (N01)","scode":"KB","shapeType":"other"},
{"value":69,"name":"Kite Double Rose Cut (N20)","scode":"KDRC","shapeType":"other"},
{"value":70,"name":"Kite Step Cut (N04)","scode":"KSC","shapeType":"other"},
{"value":71,"name":"Kite Mixed Cut (N02)","scode":"KX","shapeType":"other"},
{"value":72,"name":"Lozenge Brilliant (O01)","scode":"LB","shapeType":"other"},
{"value":73,"name":"Leaf Mixed Cut (R46)","scode":"LEAF","shapeType":"other"},
{"value":74,"name":"Lozenge Modified Brilliant (O02)","scode":"LMB","shapeType":"other"},
{"value":75,"name":"Lozenge Portrait Cut (O33)","scode":"LPC","shapeType":"other"},
{"value":76,"name":"Lozenge Step Cut (O05)","scode":"LSC","shapeType":"other"},
{"value":77,"name":"Lozenge Mixed Cut (O03)","scode":"LX","shapeType":"other"},
{"value":78,"name":"Marquise Brilliant (4M/B - B01)","scode":"MB","shapeType":"other"},
{"value":79,"name":"Marquise Double Rose Cut (B31)","scode":"MDRC","shapeType":"other"},
{"value":80,"name":"Modified Heart Brilliant (H14)","scode":"MHB","shapeType":"other"},
{"value":81,"name":"Modified Heart Double Rose Cut (H30)","scode":"MHDRC","shapeType":"other"},
{"value":82,"name":"Modified Half-Moon Brilliant Cut (P04)","scode":"MHMN","shapeType":"other"},
{"value":83,"name":"Modified Heart Rose Cut (H24)","scode":"MHRC","shapeType":"other"},
{"value":84,"name":"Modified Heart Step Cut (H17)","scode":"MHSC","shapeType":"other"},
{"value":85,"name":"Modified Heart Mixed Cut (H21)","scode":"MHX","shapeType":"other"},
{"value":86,"name":"Modified Hexagonal Brilliant (K06)","scode":"MHXB","shapeType":"round"},
{"value":87,"name":"Modified Hexagonal Portrait Cut (K17)","scode":"MHXPC","shapeType":"round"},
{"value":88,"name":"Modified Hexagonal Rose Cut (K18)","scode":"MHXRC","shapeType":"round"},
{"value":89,"name":"Modified Hexagonal Step Cut (K10)","scode":"MHXSC","shapeType":"round"},
{"value":90,"name":"Modified Hexagonal Mixed Cut (K08)","scode":"MHXX","shapeType":"round"},
{"value":91,"name":"Modified Kite Brilliant (N08)","scode":"MKB","shapeType":"other"},
{"value":92,"name":"Modified Kite Portrait Cut (N18)","scode":"MKPC","shapeType":"other"},
{"value":93,"name":"Modified Kite Step Cut (N10)","scode":"MKSC","shapeType":"other"},
{"value":94,"name":"Modified Kite Mixed Cut (N09)","scode":"MKX","shapeType":"other"},
{"value":95,"name":"Modified Lozenge Brilliant (O06)","scode":"MLB","shapeType":"other"},
{"value":96,"name":"Maple Leaf Modified Brilliant (R86)","scode":"MLMB","shapeType":"other"},
{"value":97,"name":"Modified Lozenge Step Cut (O30)","scode":"MLSC","shapeType":"other"},
{"value":98,"name":"Modified Lozenge Mixed Cut (O08)","scode":"MLX","shapeType":"other"},
{"value":99,"name":"Marquise Modified Brilliant (14M/B - B22)","scode":"MMB","shapeType":"other"},
{"value":100,"name":"Marquise Mixed Cut (B27)","scode":"MMC","shapeType":"other"},
{"value":101,"name":"Modified Marquise Double Rose Cut (B25)","scode":"MMDRC","shapeType":"other"},
{"value":102,"name":"Modified Marquise Step Cut (B13)","scode":"MMSC","shapeType":"other"},
{"value":103,"name":"Modified Marquise Mixed Cut (B12)","scode":"MMX","shapeType":"other"},
{"value":104,"name":"Marquise Novelty Cut (B26)","scode":"MNC","shapeType":"other"},
{"value":105,"name":"Modified Oval Brilliant (D45)","scode":"MOB","shapeType":"other"},
{"value":106,"name":"Modified Octahedron Cut (G109)","scode":"MOC","shapeType":"round"},
{"value":107,"name":"Modified Octagonal Brilliant (L12)","scode":"MOCB","shapeType":"round"},
{"value":108,"name":"Modified Octagonal Step Cut (L14)","scode":"MOCS","shapeType":"round"},
{"value":109,"name":"Modified Octagonal Step Cut (L21)","scode":"MOCSC","shapeType":"round"},
{"value":110,"name":"Modified Oval Step Cut (D48)","scode":"MOSC","shapeType":"other"},
{"value":111,"name":"Mouse Character Rose Cut (R18)","scode":"MOUSE","shapeType":"other"},
{"value":112,"name":"Modified Oval Mixed Cut (D47)","scode":"MOX","shapeType":"other"},
{"value":113,"name":"Modified Pear Brilliant (C18)","scode":"MPB","shapeType":"other"},
{"value":114,"name":"Marquise Portrait Cut (B24)","scode":"MPC","shapeType":"other"},
{"value":115,"name":"Modified Pear Double Rose Cut (C44)","scode":"MPDRC","shapeType":"other"},
{"value":116,"name":"Modified Pear Portrait Cut (C47)","scode":"MPPC","shapeType":"other"},
{"value":117,"name":"Modified Pear Rose Cut (C48)","scode":"MPRC","shapeType":"other"},
{"value":118,"name":"Modified Pear Step Cut (C21)","scode":"MPSC","shapeType":"other"},
{"value":119,"name":"Modified Pentagonal Brilliant (J05)","scode":"MPTB","shapeType":"other"},
{"value":120,"name":"Modified Pentagonal Step Cut (J06)","scode":"MPTSC","shapeType":"other"},
{"value":121,"name":"Modified Pentagonal Mixed Cut (J09)","scode":"MPTX","shapeType":"other"},
{"value":122,"name":"Modified Pear Mixed Cut (C20)","scode":"MPX","shapeType":"other"},
{"value":123,"name":"Modified Rectangular Brilliant (E28)","scode":"MRB","shapeType":"other"},
{"value":124,"name":"Marquise Rose Cut (B20)","scode":"MRC","shapeType":"other"},
{"value":125,"name":"Modified Rhomboid Brilliant (J43)","scode":"MRHB","shapeType":"other"},
{"value":126,"name":"Modified Rectangular Mixed Cut (E131)","scode":"MRMC","shapeType":"other"},
{"value":127,"name":"Modified Rectangular Novelty Cut (E88)","scode":"MRNC","shapeType":"other"},
{"value":128,"name":"Modified Rectangular Step Cut (E38)","scode":"MRSC","shapeType":"other"},
{"value":129,"name":"Modified Square Brilliant (G110)","scode":"MSB","shapeType":"other"},
{"value":130,"name":"Marquise Step Cut (B21)","scode":"MSC","shapeType":"other"},
{"value":131,"name":"Modified Shield Brilliant (M04)","scode":"MSHB","shapeType":"other"},
{"value":132,"name":"Modified Shield Novelty Cut (M52)","scode":"MSHNC","shapeType":"other"},
{"value":133,"name":"Modified Shield Portrait Cut (M28)","scode":"MSHPC","shapeType":"other"},
{"value":134,"name":"Modified Shield Rose Cut (M25)","scode":"MSHRC","shapeType":"other"},
{"value":135,"name":"Modified Shield Step Cut (M07)","scode":"MSHSC","shapeType":"other"},
{"value":136,"name":"Modified Shield Mixed Cut (M06)","scode":"MSHX","shapeType":"other"},
{"value":137,"name":"Modified Shield Novelty Cut (M26)","scode":"MSNC","shapeType":"other"},
{"value":138,"name":"Modified Shield Portrait Cut (M41)","scode":"MSPC","shapeType":"other"},
{"value":139,"name":"Modified Square Step Cut (G52)","scode":"MSSC","shapeType":"other"},
{"value":140,"name":"Modified Seven-Sided Novelty","scode":"MSSN","shapeType":"other"},
{"value":141,"name":"Modified Triangular Novelty Cut (I25)","scode":"MTNC","shapeType":"other"},
{"value":142,"name":"Modified Trapezoid Brilliant (T09)","scode":"MTPB","shapeType":"other"},
{"value":143,"name":"Modified Trapezoid Mixed Cut (T04)","scode":"MTPX","shapeType":"other"},
{"value":144,"name":"Modified Triangular Brilliant (I03)","scode":"MTRB","shapeType":"other"},
{"value":145,"name":"Modified Triangular Double Rose Cut (I31)","scode":"MTRDC","shapeType":"other"},
{"value":146,"name":"Modified Triangular Rose Cut (I28)","scode":"MTRRC","shapeType":"other"},
{"value":147,"name":"Modified Triangular Step Cut (I12)","scode":"MTRSC","shapeType":"other"},
{"value":148,"name":"Modified Triangular Mixed Cut (I10)","scode":"MTRX","shapeType":"other"},
{"value":149,"name":"Nine-Sided Modified Brilliant (L25)","scode":"NSMB","shapeType":"round"},
{"value":150,"name":"Oval Brilliant (4M - D01)","scode":"OB","shapeType":"other"},
{"value":151,"name":"Octagonal Brilliant (L01)","scode":"OCB","shapeType":"round"},
{"value":152,"name":"Octagonal Modified Brilliant (L03)","scode":"OCMB","shapeType":"round"},
{"value":153,"name":"Octagonal Portrait Cut (L07)","scode":"OCPC","shapeType":"round"},
{"value":154,"name":"Octagonal Step Cut (L06)","scode":"OCSC","shapeType":"round"},
{"value":155,"name":"Octagonal Mixed Cut (L04)","scode":"OCX","shapeType":"round"},
{"value":156,"name":"Oval Double Rose Cut (D56)","scode":"ODRC","shapeType":"other"},
{"value":157,"name":"Old European Brilliant (A09)","scode":"OEB","shapeType":"other"},
{"value":158,"name":"Old Mine Brilliant (F01)","scode":"OMB","shapeType":"other"},
{"value":159,"name":"Oval Modified Portrait Cut (D52)","scode":"OMPC","shapeType":"other"},
{"value":160,"name":"Oval Novelty Cut (D58)","scode":"ONC","shapeType":"other"},
{"value":161,"name":"Oval Portrait Cut (D50)","scode":"OPC","shapeType":"other"},
{"value":162,"name":"Oval Rose Cut (D44)","scode":"ORC","shapeType":"other"},
{"value":163,"name":"Oval Step Cut (D41)","scode":"OSC","shapeType":"other"},
{"value":164,"name":"Arrow Novelty Cut (R91)","scode":"OTH","shapeType":"other"},
{"value":165,"name":"Oval Mixed Cut (D42)","scode":"OX","shapeType":"other"},
{"value":166,"name":"Pear Brilliant (4M/B - C01)","scode":"PB","shapeType":"other"},
{"value":167,"name":"Pear Double Rose Cut (C27)","scode":"PDRC","shapeType":"other"},
{"value":168,"name":"Pear Modified Brilliant (C14)","scode":"PMB","shapeType":"other"},
{"value":169,"name":"Pear Novelty Cut (C54)","scode":"PNC","shapeType":"other"},
{"value":170,"name":"Pear Portrait Cut (C32)","scode":"PPC","shapeType":"other"},
{"value":171,"name":"Pear Rose Cut (C17)","scode":"PRC","shapeType":"other"},
{"value":172,"name":"Pear Step Cut (C31)","scode":"PSC","shapeType":"other"},
{"value":173,"name":"Pentagonal Modified Brilliant (J02)","scode":"PTMB","shapeType":"other"},
{"value":174,"name":"Pentagonal Step Cut (J04)","scode":"PTSC","shapeType":"other"},
{"value":175,"name":"Pentagonal Mixed Cut (J03)","scode":"PTX","shapeType":"other"},
{"value":176,"name":"Pear Mixed Cut (C30)","scode":"PX","shapeType":"other"},
{"value":177,"name":"Round Modified Brilliant (A116)","scode":"R","shapeType":"round"},
{"value":178,"name":"Round Brilliant (A01)","scode":"RBC","shapeType":"round"},
{"value":179,"name":"Racket Modified Brilliant (R04)","scode":"RCKT","shapeType":"other"},
{"value":180,"name":"Round-Cornered Rectangular Brilliant (E23)","scode":"RCRB","shapeType":"other"},
{"value":181,"name":"Round-Cornered Rhomboid Mixed Cut (J08)","scode":"RCRHX","shapeType":"other"},
{"value":182,"name":"Round-Cornered Rectangular Modified Brilliant (E128)","scode":"RCRMB","shapeType":"other"},
{"value":183,"name":"Round-Cornered Rectangular Portrait Cut (E100)","scode":"RCRPC","shapeType":"other"},
{"value":184,"name":"Round-Cornered Rectangular Step Cut (E26)","scode":"RCRSC","shapeType":"other"},
{"value":185,"name":"Round-Cornered Rectangular Mixed Cut (E25)","scode":"RCRX","shapeType":"other"},
{"value":186,"name":"Round-Cornered Square Brilliant (G97)","scode":"RCSB","shapeType":"other"},
{"value":187,"name":"Round-Cornered Square Modified Brilliant (G128)","scode":"RCSMB","shapeType":"other"},
{"value":188,"name":"Round-Cornered Square Step Cut (G23)","scode":"RCSSC","shapeType":"other"},
{"value":189,"name":"Round-Cornered Square Mixed Cut (G21)","scode":"RCSX","shapeType":"other"},
{"value":190,"name":"Rectangular Novelty Cut (E132)","scode":"RENC","shapeType":"other"},
{"value":191,"name":"Rhomboid Step Cut (J01)","scode":"RHSC","shapeType":"other"},
{"value":192,"name":"Modified Round Brilliant (A75)","scode":"RMB","shapeType":"round"},
{"value":193,"name":"Round Novelty Cut (A104)","scode":"RNC","shapeType":"round"},
{"value":194,"name":"Rectangular Portrait Cut (E72)","scode":"RPC","shapeType":"other"},
{"value":195,"name":"Round Rose Cut (A106)","scode":"RRC","shapeType":"other"},
{"value":196,"name":"Rectangular Step Cut (E02)","scode":"RSC","shapeType":"other"},
{"value":197,"name":"Round Cornered Triangular Modified Brilliant (I17)","scode":"RTRMB","shapeType":"other"},
{"value":198,"name":"Rectangular Mixed Cut (E03)","scode":"RX","shapeType":"other"},
{"value":199,"name":"Square Emerald Cut (3 Step, G85)","scode":"SEM","shapeType":"other"},
{"value":200,"name":"Scalloped Edge Round Brilliant (R19)","scode":"SERB","shapeType":"round"},
{"value":201,"name":"Shield Brilliant (M01)","scode":"SHB","shapeType":"other"},
{"value":202,"name":"Shield Step Cut (M03)","scode":"SHSC","shapeType":"other"},
{"value":203,"name":"Shield Mixed Cut (M02)","scode":"SHX","shapeType":"other"},
{"value":204,"name":"Square Modified Brilliant (G103)","scode":"SMB","shapeType":"other"},
{"value":205,"name":"Square Novelty Cut (G84)","scode":"SNC","shapeType":"other"},
{"value":206,"name":"Seven-Sided Brilliant (HP1)","scode":"SSB","shapeType":"other"},
{"value":207,"name":"Square Step Cut (G01)","scode":"SSC","shapeType":"other"},
{"value":208,"name":"Modified Star Brilliant (R15)","scode":"STAR","shapeType":"other"},
{"value":209,"name":"Square Mixed Cut (G123)","scode":"SX","shapeType":"other"},
{"value":210,"name":"Tapered Baguette (T03)","scode":"TAPBA","shapeType":"other"},
{"value":211,"name":"Tetrahedral Cut (I35)","scode":"THC","shapeType":"other"},
{"value":212,"name":"Trapezoid Modified Brilliant (T01)","scode":"TPMB","shapeType":"other"},
{"value":213,"name":"Trapezoid Portrait Cut (T08)","scode":"TPPC","shapeType":"other"},
{"value":214,"name":"Trapezoid Step Cut (T05)","scode":"TPSC","shapeType":"other"},
{"value":215,"name":"Triangular Brilliant (I01)","scode":"TRB","shapeType":"other"},
{"value":216,"name":"Tree Novelty Cut (R03)","scode":"TREE","shapeType":"other"},
{"value":217,"name":"Triangular Mixed Cut (I21)","scode":"TRIX","shapeType":"other"},
{"value":218,"name":"Triangular Modified Brilliant (I02)","scode":"TRMB","shapeType":"other"},
{"value":219,"name":"Triangular Portrait Cut (I30)","scode":"TRPC","shapeType":"other"},
{"value":220,"name":"Triangular Step Cut (I18)","scode":"TRSC","shapeType":"other"}];
            return diamondShapes;
        },
        gemstoneCuts : function () { //Array of gemstone cuts
            var gemstoneCuts = [  
                    {'value': 1, 'name': "Faceted"},
                    {'value': 2, 'name': "Cabochon"},
                    {'value': 3, 'name': "Cameo"},
                    {'value': 4, 'name': "Intaglio"},
                    {'value': 5, 'name': "Chevee"},
                    {'value': 6, 'name': "Cuvette"},
                    {'value': 7, 'name': "Bead"},
                    ];
            return gemstoneCuts;
        },
        enhancement : function () { //Array of enhancement
            var enhancement = [  
                    {'value': 1, 'name': "Natural"},
                    {'value': 2, 'name': "Irradiation"},
                    {'value': 3, 'name': "Fracture Filled"},
                    {'value': 4, 'name': "Surface Dyes"},
                    {'value': 5, 'name': "Beryllium"},
                    {'value': 6, 'name': "Heat Treatment"}
                    ];
            return enhancement;
        },
        externalInclusions : function () { //Array of external Inclusions
            var externalInclusions = [  
                    {'value': 1, 'name': "Pit"},
                    {'value': 2, 'name': "Cavity"},
                    {'value': 3, 'name': "Chip"},
                    {'value': 4, 'name': "Nick"},
                    {'value': 5, 'name': "Surface Grain Line"},
                    {'value': 6, 'name': "Scratch"},
                    {'value': 7, 'name': "Extra Facet"},
                    {'value': 8, 'name': "Other"}
                    ];
            return externalInclusions;
        },
        internalInclusions : function () { //Array of internal Inclusions
            var externalInclusions = [  
                    {'value': 1, 'name': "Feather"},
                    {'value': 2, 'name': "Crystal"},
                    {'value': 3, 'name': "Dark Crystal"},
                    {'value': 4, 'name': "Pinpoint Single"},
                    {'value': 5, 'name': "Pinpoint Cluster"},
                    {'value': 6, 'name': "Cloud"},
                    {'value': 7, 'name': "Knot"},
                    {'value': 8, 'name': "Bruise"},
                    {'value': 9, 'name': "Internal Grain Line"},
                    {'value': 10, 'name': "Feathered Girdle"},
                    {'value': 11, 'name': "Laser Drill Hole"},
                    {'value': 12, 'name': "Cavity"},
                    {'value': 13, 'name': "Wisp"},
                    {'value': 14, 'name': "Indented Natural"},
                    {'value': 15, 'name': "Needle-like"}
                    ];
            return externalInclusions;
        },
        gemstoneType : function () { //Array of diamonds for consumer form
            var gemstoneType = [  
                        {'value': 1, 'name': "Alexandrite",'group':''},
                        {'value': 2, 'name': "Andalusite",'group':''},
                        {'value': 3, 'name': "Axinite",'group':''},
                        {'value': 4, 'name': "Benitoite",'group':''},
                        {'value': 5, 'name': "Aquamarine",'group':'Beryl'},
                        {'value': 6, 'name': "Bixbite",'group':'Beryl'},
                        {'value': 7, 'name': "Emerald",'group':'Beryl'},
                        {'value': 8, 'name': "Morganite",'group':'Beryl'},
                        {'value': 9, 'name': "Bloodstone",'group':''},
                        {'value': 10, 'name': "Cassiterite",'group':''},
                        {'value': 11, 'name': "Celestite",'group':''},
                        {'value': 12, 'name': "Cat's Eye",'group':'Chrysoberyl'},
                        {'value': 13, 'name': "Chrysocolla",'group':''},
                        {'value': 14, 'name': "Chrysoprase",'group':''},
                        {'value': 15, 'name': "Clinohumite",'group':''},
                        {'value': 16, 'name': "Cordierite",'group':''},
                        {'value': 17, 'name': "Ruby",'group':'Corundum'},
                        {'value': 18, 'name': "Sapphire",'group':'Corundum'},
                        {'value': 19, 'name': "Danburite",'group':''},
                        {'value': 20, 'name': "Diamond",'group':''},
                        {'value': 21, 'name': "Diopside",'group':''},
                        {'value': 22, 'name': "Dioptase",'group':''},
                        {'value': 23, 'name': "Dumortierite",'group':''},
                        {'value': 24, 'name': "Amazonite",'group':'Feldspar'},
                        {'value': 25, 'name': "Labradorite",'group':'Feldspar'},
                        {'value': 26, 'name': "Moonstone",'group':'Feldspar'},
                        {'value': 27, 'name': "Sunstone",'group':'Feldspar'},
                        {'value': 28, 'name': "Fluorite",'group':''},
                        {'value': 29, 'name': "Hessonite",'group':'Garnet'},
                        {'value': 30, 'name': "Hambergite",'group':''},
                        {'value': 31, 'name': "Hematite",'group':''},
                        {'value': 32, 'name': "Jadeite",'group':'Jade'},
                        {'value': 33, 'name': "Nephrite",'group':'Jade'},
                        {'value': 34, 'name': "Jasper",'group':''},
                        {'value': 35, 'name': "Kornerupine",'group':''},
                        {'value': 36, 'name': "Kunzite",'group':''},
                        {'value': 37, 'name': "Malachite",'group':''},
                        {'value': 38, 'name': "Peridot",'group':''},
                        {'value': 39, 'name': "Prehnite",'group':''},
                        {'value': 40, 'name': "Pyrite",'group':''},
                        {'value': 41, 'name': "Amethyst",'group':'Quartz'},
                        {'value': 42, 'name': "Citrine",'group':'Quartz'},
                        {'value': 43, 'name': "Smoky Quartz",'group':'Quartz'},
                        {'value': 44, 'name': "Tiger's-eye",'group':'Quartz'},
                        {'value': 45, 'name': "Agate (Chalcedony)",'group':'Quartz'},
                        {'value': 46, 'name': "Aventurine (Chalcedony)",'group':'Quartz'},
                        {'value': 47, 'name': "Onyx (Chalcedony)",'group':'Quartz'},
                        {'value': 48, 'name': "Rhodochrosite",'group':''},
                        {'value': 49, 'name': "Sérandite",'group':''},
                        {'value': 50, 'name': "Spinel",'group':''},
                        {'value': 51, 'name': "Sugilite",'group':''},
                        {'value': 52, 'name': "Topaz",'group':''},
                        {'value': 53, 'name': "Turquoise",'group':''},
                        {'value': 54, 'name': "Tourmaline",'group':''},
                        {'value': 55, 'name': "Variscite",'group':''},
                        {'value': 56, 'name': "Vesuvianite",'group':''},
                        {'value': 57, 'name': "Xenotime",'group':''},
                        {'value': 58, 'name': "Zeolite (Thomsonite)",'group':''},
                        {'value': 59, 'name': "Zircon",'group':''},
                        {'value': 60, 'name': "Tanzanite",'group':'Zoisite'},
                        {'value': 61, 'name': "Thulite",'group':'Zoisite'},
                    ];
            return gemstoneType;
        },
        purityType : function () { //Array of diamonds for consumer form
            var purity = [  
                    {'value': 1, 'name': "24k",'group':'Gold'},
                    {'value': 2, 'name': "22k",'group':'Gold'},
                    {'value': 3, 'name': "22k Coins",'group':'Gold'},
                    {'value': 4, 'name': "900 Coins",'group':'Gold'},
                    {'value': 5, 'name': "21k",'group':'Gold'},
                    {'value': 6, 'name': "18k",'group':'Gold'},
                    {'value': 7, 'name': "16k",'group':'Gold'},
                    {'value': 8, 'name': "14k",'group':'Gold'},
                    {'value': 9, 'name': "12k",'group':'Gold'},
                    {'value': 10, 'name': "10k",'group':'Gold'},
                    {'value': 11, 'name': "9k",'group':'Gold'},
                    {'value': 12, 'name': "Pure",'group':'Silver'},
                    {'value': 13, 'name': "Sterling",'group':'Silver'},
                    {'value': 14, 'name': "800 Silver",'group':'Silver'},
                    {'value': 15, 'name': "600 Silver",'group':'Silver'},
                    {'value': 16, 'name': "400 Silver",'group':'Silver'},
                    {'value': 17, 'name': "Pure",'group':'Platinum'},
                    {'value': 18, 'name': "90%",'group':'Platinum'}
                    ];
            return purity;
        },
        metalType : function () { //Array of diamonds for consumer form
            var metalType = [  
                    {'value': 1, 'name': "Gold"},
                    {'value': 2, 'name': "Silver"},
                    {'value': 3, 'name': "Platinum"},
                    {'value': 4, 'name': "Rhodium"},
                    {'value': 5, 'name': "Palladium"},
                    {'value': 6, 'name': "Titanium"},
                    {'value': 7, 'name': "Tungsten"},
                    {'value': 8, 'name': "Stainless Steel"},
                    {'value': 9, 'name': "Gold Filled"},
                    {'value': 10, 'name': "Gold Plated"},
                    {'value': 11, 'name': "Rhodium Plated"},
                    {'value': 12, 'name': "Other"}
                    ];
            return metalType;
        },
        blemish : function () { //Array of diamonds for consumer form
            var blemish = [  
                    {'value': 1, 'name': "Clean"},
                    {'value': 2, 'name': "Lightly Blemished"},
                    {'value': 3, 'name': "Moderately Blemished"},
                    {'value': 4, 'name': "Heavily Blemished"} 
                    ];
            return blemish;
        },
        metalColor : function () { //Array of diamonds for consumer form
            var metalColor = [  
                    {'value': 1, 'name': "Yellow"},
                    {'value': 2, 'name': "White"},
                    {'value': 3, 'name': "White Gold With Black Rhodium"},
                    {'value': 4, 'name': "Rose"},
                    {'value': 5, 'name': "Vermeil"},
                    {'value': 6, 'name': "Two Tone"},
                    {'value': 7, 'name': "Tri Color"}
                    ];
            return metalColor;
        },
        typeDetermined : function () { //Array of diamonds for consumer form
            var typeDetermined = [  
                        {'value': 1, 'name': "Stamped"},
                        {'value': 2, 'name': "Tested"},
                        {'value': 3, 'name': "Other"},
                    ];
            return typeDetermined;
        },
        
        pearlColor : function () { //Array of diamonds for consumer form
            var pearlColor = [  
                    {'value': 1, 'name': "White - Rose",'group':'White'},
                    {'value': 2, 'name': "White - Silver",'group':'White'},
                    {'value': 3, 'name': "White - Cream",'group':'White'},
                    {'value': 4, 'name': "White - Ivory",'group':'White'},
                    {'value': 5, 'name': "White - Purplish",'group':'White'},
                    {'value': 6, 'name': "White - Pink",'group':'White'},
                    {'value': 7, 'name': "White - Peach",'group':'White'},
                    {'value': 8, 'name': "White - Lavender",'group':'White'},
                    {'value': 9, 'name': "Black - Pale Silver",'group':'Black'},
                    {'value': 10, 'name': "Black - Dove Grey",'group':'Black'},
                    {'value': 11, 'name': "Black - Very Dark Charcoal Grey",'group':'Black'},
                    {'value': 12, 'name': "Black - Peacock (mix of Green Gold Pink hues)",'group':'Black'},
                    {'value': 13, 'name': "Black - Silver/Steel",'group':'Black'},
                    {'value': 14, 'name': "Black - Blue-Green",'group':'Black'},
                    {'value': 15, 'name': "Black - Eggplant Purple",'group':'Black'},
                    {'value': 16, 'name': "Black - Cherry",'group':'Black'},
                    {'value': 17, 'name': "Black - Sky Blue",'group':'Black'},
                    {'value': 18, 'name': "Black - Pistachio",'group':'Black'},
                    {'value': 19, 'name': "Black - Chocolate",'group':'Black'},
                    {'value': 20, 'name': "Black - Multi Color",'group':'Black'},
                    {'value': 21, 'name': "Golden - Neutral Golden",'group':'Golden'},
                    {'value': 22, 'name': "Golden - Champagne",'group':'Golden'},
                    {'value': 23, 'name': "Golden - Green/Bronze",'group':'Golden'},
                    {'value': 24, 'name': "Golden - Rose",'group':'Golden'},
                    {'value': 25, 'name': "Golden - Pink",'group':'Golden'},
                    {'value': 26, 'name': "Golden - Peach",'group':'Golden'}
                ]
                 return pearlColor;
        },
        
        pearlType : function () { //Array of diamonds for consumer form
            var pearlType = [  
                    {'value': 1, 'name': "Cultured"},
                    {'value': 2, 'name': "Freshwater Cultured"},
                    {'value': 3, 'name': "Mabe"},
                    {'value': 4, 'name': "South Sea Cultured"},
                    {'value': 5, 'name': "Natural"},
                    {'value': 6, 'name': "Imitation"},
                    {'value': 7, 'name': "Seed Pearl"},
                    {'value': 8, 'name': "Salt Water Cultured"},
                    {'value': 9, 'name': "Akoya"}
                    ];
            return pearlType;
        },
        pearlsStyle : function () { //Array of diamonds for consumer form
            var pearlsStyle = [  
                    {'value': 1, 'name': "Single"},
                    {'value': 2, 'name': "Double"},
                    {'value': 3, 'name': "Triple"},
                    {'value': 4, 'name': "Other"}
                    ];
            return pearlsStyle;
        },
        priceAdjustmentOperator : function () { //Array of diamonds for consumer form
            var operator = [  
                        {'value': 1, 'name': "+"},
                        {'value': 2, 'name': "-"},
                    ];
            return operator;
        },
        priceAdjustmentType : function () { //Array of diamonds for consumer form
            var adjustmentType = [  
                        {'value': 1, 'name': "USD"},
                        {'value': 2, 'name': "%"},
                    ];
            return adjustmentType;
        },
        countryCode : function () { //Array of Country code
            var countryCode = [  
                        {'value': 1, 'name': "United States (US)"},
                        {'value': 1, 'name': "Canada (CA)"},
                        {'value': 7, 'name': "Abkhazia (GE)"},
                        {'value': 93, 'name': "Afghanistan (AF)"},
                        {'value': 355, 'name': "Albania (AL)"},
                        {'value': 213, 'name': "Algeria (DZ)"},
                        {'value': 684, 'name': "American Samoa (AS)"},
                        {'value': 376, 'name': "Andorra (AD)"},
                        {'value': 244, 'name': "Angola (AO)"},
                        {'value': 1264, 'name': "Anguilla (AI)"},
                        {'value': 1268, 'name': "Antigua and Barbuda (AG)"},
                        {'value': 54, 'name': "Argentina Republic (AR)"},
                        {'value': 374, 'name': "Armenia (AM)"},
                        {'value': 297, 'name': "Aruba (AW)"},
                        {'value': 61, 'name': "Australia (AU)"},
                        {'value': 43, 'name': "Austria (AT)"},
                        {'value': 994, 'name': "Azerbaijan (AZ)"},
                        {'value': 1242, 'name': "Bahamas (BS)"},
                        {'value': 973, 'name': "Bahrain (BH)"},
                        {'value': 880, 'name': "Bangladesh (BD)"},
                        {'value': 1246, 'name': "Barbados (BB)"},
                        {'value': 375, 'name': "Belarus (BY)"},
                        {'value': 32, 'name': "Belgium (BE)"},
                        {'value': 501, 'name': "Belize (BZ)"},
                        {'value': 229, 'name': "Benin (BJ)"},
                        {'value': 1441, 'name': "Bermuda (BM)"},
                        {'value': 975, 'name': "Bhutan (BT)"},
                        {'value': 591, 'name': "Bolivia (BO)"},
                        {'value': 387, 'name': "Bosnia & Herzegov. (BA)"},
                        {'value': 267, 'name': "Botswana (BW)"},
                        {'value': 55, 'name': "Brazil (BR)"},
                        {'value': 284, 'name': "British Virgin Islands (VG)"},
                        {'value': 673, 'name': "Brunei Darussalam (BN)"},
                        {'value': 359, 'name': "Bulgaria (BG)"},
                        {'value': 226, 'name': "Burkina Faso (BF)"},
                        {'value': 257, 'name': "Burundi (BI)"},
                        {'value': 855, 'name': "Cambodia (KH)"},
                        {'value': 237, 'name': "Cameroon (CM)"},
                        {'value': 238, 'name': "Cape Verde (CV)"},
                        {'value': 1345, 'name': "Cayman Islands (KY)"},
                        {'value': 236, 'name': "Central African Rep. (CF)"},
                        {'value': 235, 'name': "Chad (TD)"},
                        {'value': 56, 'name': "Chile (CL)"},
                        {'value': 86, 'name': "China (CN)"},
                        {'value': 57, 'name': "Colombia (CO)"},
                        {'value': 269, 'name': "Comoros (KM)"},
                        {'value': 243, 'name': "Congo, Dem. Rep. (CD)"},
                        {'value': 242, 'name': "Congo, Republic (CG)"},
                        {'value': 682, 'name': "Cook Islands (CK)"},
                        {'value': 506, 'name': "Costa Rica (CR)"},
                        {'value': 385, 'name': "Croatia (HR)"},
                        {'value': 53, 'name': "Cuba (CU)"},
                        {'value': 599, 'name': "Curacao (CW)"},
                        {'value': 357, 'name': "Cyprus (CY)"},
                        {'value': 420, 'name': "Czech Rep. (CZ)"},
                        {'value': 45, 'name': "Denmark (DK)"},
                        {'value': 253, 'name': "Djibouti (DJ)"},
                        {'value': 1767, 'name': "Dominica (DM)"},
                        {'value': 1809, 'name': "Dominican Republic (DO)"},
                        {'value': 593, 'name': "Ecuador (EC)"},
                        {'value': 20, 'name': "Egypt (EG)"},
                        {'value': 503, 'name': "El Salvador (SV)"},
                        {'value': 240, 'name': "Equatorial Guinea (GQ)"},
                        {'value': 291, 'name': "Eritrea (ER)"},
                        {'value': 372, 'name': "Estonia (EE)"},
                        {'value': 251, 'name': "Ethiopia (ET)"},
                        {'value': 500, 'name': "Falkland Islands (Malvinas) (FK)"},
                        {'value': 298, 'name': "Faroe Islands (FO)"},
                        {'value': 679, 'name': "Fiji (FJ)"},
                        {'value': 358, 'name': "Finland (FI)"},
                        {'value': 33, 'name': "France (FR)"},
                        {'value': 594, 'name': "French Guiana (FG)"},
                        {'value': 689, 'name': "French Polynesia (PF)"},
                        {'value': 241, 'name': "Gabon (GA)"},
                        {'value': 220, 'name': "Gambia (GM)"},
                        {'value': 995, 'name': "Georgia (GE)"},
                        {'value': 49, 'name': "Germany (DE)"},
                        {'value': 233, 'name': "Ghana (GH)"},
                        {'value': 350, 'name': "Gibraltar (GI)"},
                        {'value': 30, 'name': "Greece (GR)"},
                        {'value': 299, 'name': "Greenland (GL)"},
                        {'value': 1473, 'name': "Grenada (GD)"},
                        {'value': 590, 'name': "Guadeloupe (GP)"},
                        {'value': 1671, 'name': "Guam (GU)"},
                        {'value': 502, 'name': "Guatemala (GT)"},
                        {'value': 224, 'name': "Guinea (GN)"},
                        {'value': 245, 'name': "Guinea-Bissau (GW)"},
                        {'value': 592, 'name': "Guyana (GY)"},
                        {'value': 509, 'name': "Haiti (HT)"},
                        {'value': 504, 'name': "Honduras (HN)"},
                        {'value': 852, 'name': "Hongkong, China (HK)"},
                        {'value': 36, 'name': "Hungary (HU)"},
                        {'value': 354, 'name': "Iceland (IS)"},
                        {'value': 91, 'name': "India (IN)"},
                        {'value': 62, 'name': "Indonesia (ID)"},
                        {'value': 98, 'name': "Iran (IR)"},
                        {'value': 964, 'name': "Iraq (IQ)"},
                        {'value': 353, 'name': "Ireland (IE)"},
                        {'value': 972, 'name': "Israel (IL)"},
                        {'value': 39, 'name': "Italy (IT)"},
                        {'value': 225, 'name': "Ivory Coast (CI)"},
                        {'value': 1876, 'name': "Jamaica (JM)"},
                        {'value': 81, 'name': "Japan (JP)"},
                        {'value': 962, 'name': "Jordan (JO)"},
                        {'value': 7, 'name': "Kazakhstan (KZ)"},
                        {'value': 254, 'name': "Kenya (KE)"},
                        {'value': 686, 'name': "Kiribati (KI)"},
                        {'value': 850, 'name': "Korea N., Dem. People's Rep. (KP)"},
                        {'value': 82, 'name': "Korea S, Republic of (KR)"},
                        {'value': 965, 'name': "Kuwait (KW)"},
                        {'value': 996, 'name': "Kyrgyzstan (KG)"},
                        {'value': 856, 'name': "Laos P.D.R. (LA)"},
                        {'value': 371, 'name': "Latvia (LV)"},
                        {'value': 961, 'name': "Lebanon (LB)"},
                        {'value': 266, 'name': "Lesotho (LS)"},
                        {'value': 231, 'name': "Liberia (LR)"},
                        {'value': 218, 'name': "Libya (LY)"},
                        {'value': 423, 'name': "Liechtenstein (LI)"},
                        {'value': 370, 'name': "Lithuania (LT)"},
                        {'value': 352, 'name': "Luxembourg (LU)"},
                        {'value': 853, 'name': "Macao, China (MO)"},
                        {'value': 389, 'name': "Macedonia (MK)"},
                        {'value': 261, 'name': "Madagascar (MG)"},
                        {'value': 265, 'name': "Malawi (MW)"},
                        {'value': 60, 'name': "Malaysia (MY)"},
                        {'value': 960, 'name': "Maldives (MV)"},
                        {'value': 223, 'name': "Mali (ML)"},
                        {'value': 356, 'name': "Malta (MT)"},
                        {'value': 596, 'name': "Martinique (French Department of) (MQ)"},
                        {'value': 222, 'name': "Mauritania (MR)"},
                        {'value': 230, 'name': "Mauritius (MU)"},
                        {'value': 52, 'name': "Mexico (MX)"},
                        {'value': 691, 'name': "Micronesia (FM)"},
                        {'value': 373, 'name': "Moldova (MD)"},
                        {'value': 377, 'name': "Monaco (MC)"},
                        {'value': 976, 'name': "Mongolia (MN)"},
                        {'value': 382, 'name': "Montenegro (ME)"},
                        {'value': 1664, 'name': "Montserrat (MS)"},
                        {'value': 212, 'name': "Morocco (MA)"},
                        {'value': 258, 'name': "Mozambique (MZ)"},
                        {'value': 95, 'name': "Myanmar (Burma) (MM)"},
                        {'value': 264, 'name': "Namibia (NA)"},
                        {'value': 977, 'name': "Nepal (NP)"},
                        {'value': 31, 'name': "Netherlands (NL)"},
                        {'value': 599, 'name': "Netherlands Antilles (AN)"},
                        {'value': 687, 'name': "New Caledonia (NC)"},
                        {'value': 64, 'name': "New Zealand (NZ)"},
                        {'value': 505, 'name': "Nicaragua (NI)"},
                        {'value': 227, 'name': "Niger (NE)"},
                        {'value': 234, 'name': "Nigeria (NG)"},
                        {'value': 683, 'name': "Niue (NU)"},
                        {'value': 47, 'name': "Norway (NO)"},
                        {'value': 968, 'name': "Oman (OM)"},
                        {'value': 92, 'name': "Pakistan (PK)"},
                        {'value': 680, 'name': "Palau (Republic of) (PW)"},
                        {'value': 970, 'name': "Palestinian Territory (PS)"},
                        {'value': 507, 'name': "Panama (PA)"},
                        {'value': 675, 'name': "Papua New Guinea (PG)"},
                        {'value': 595, 'name': "Paraguay (PY)"},
                        {'value': 51, 'name': "Peru (PE)"},
                        {'value': 63, 'name': "Philippines (PH)"},
                        {'value': 48, 'name': "Poland (PL)"},
                        {'value': 351, 'name': "Portugal (PT)"},
                        {'value': 974, 'name': "Qatar (QA)"},
                        {'value': 262, 'name': "Reunion (RE)"},
                        {'value': 40, 'name': "Romania (RO)"},
                        {'value': 79, 'name': "Russian Federation (RU)"},
                        {'value': 250, 'name': "Rwanda (RW)"},
                        {'value': 1869, 'name': "Saint Kitts and Nevis (KN)"},
                        {'value': 1758, 'name': "Saint Lucia (LC)"},
                        {'value': 685, 'name': "Samoa (WS)"},
                        {'value': 378, 'name': "San Marino (SM)"},
                        {'value': 239, 'name': "Sao Tome & Principe (ST)"},
                        {'value': 870, 'name': "Satellite Networks (N/A)"},
                        {'value': 966, 'name': "Saudi Arabia (SA)"},
                        {'value': 221, 'name': "Senegal (SN)"},
                        {'value': 381, 'name': "Serbia (RS)"},
                        {'value': 248, 'name': "Seychelles (SC)"},
                        {'value': 232, 'name': "Sierra Leone (SL)"},
                        {'value': 65, 'name': "Singapore (SG)"},
                        {'value': 421, 'name': "Slovakia (SK)"},
                        {'value': 386, 'name': "Slovenia (SI)"},
                        {'value': 677, 'name': "Solomon Islands (SB)"},
                        {'value': 252, 'name': "Somalia (SO)"},
                        {'value': 27, 'name': "South Africa (ZA)"},
                        {'value': 34, 'name': "Spain (ES)"},
                        {'value': 94, 'name': "Sri Lanka (LK)"},
                        {'value': 508, 'name': "St. Pierre & Miquelon (PM)"},
                        {'value': 1784, 'name': "St. Vincent & Gren. (VC)"},
                        {'value': 249, 'name': "Sudan (SD)"},
                        {'value': 597, 'name': "Suriname (SR)"},
                        {'value': 268, 'name': "Swaziland (SZ)"},
                        {'value': 46, 'name': "Sweden (SE)"},
                        {'value': 41, 'name': "Switzerland (CH)"},
                        {'value': 963, 'name': "Syrian Arab Republic (SY)"},
                        {'value': 886, 'name': "Taiwan (TW)"},
                        {'value': 992, 'name': "Tajikistan (TK)"},
                        {'value': 255, 'name': "Tanzania (TZ)"},
                        {'value': 66, 'name': "Thailand (TH)"},
                        {'value': 670, 'name': "Timor-Leste (TP)"},
                        {'value': 228, 'name': "Togo (TG)"},
                        {'value': 676, 'name': "Tonga (TO)"},
                        {'value': 1868, 'name': "Trinidad and Tobago (TT)"},
                        {'value': 216, 'name': "Tunisia (TN)"},
                        {'value': 90, 'name': "Turkey (TR)"},
                        {'value': 993, 'name': "Turkmenistan (TM)"},
                        {'value': 256, 'name': "Uganda (UG)"},
                        {'value': 380, 'name': "Ukraine (UA)"},
                        {'value': 971, 'name': "United Arab Emirates (AE)"},
                        {'value': 44, 'name': "United Kingdom (GB)"},
                        {'value': 598, 'name': "Uruguay (UY)"},
                        {'value': 998, 'name': "Uzbekistan (UZ)"},
                        {'value': 678, 'name': "Vanuatu (VU)"},
                        {'value': 58, 'name': "Venezuela (VE)"},
                        {'value': 84, 'name': "Viet Nam (VN)"},
                        {'value': 1340, 'name': "Virgin Islands, U.S. (VI)"},
                        {'value': 967, 'name': "Yemen (YE)"},
                        {'value': 260, 'name': "Zambia (ZM)"},
                        {'value': 263, 'name': "Zimbabwe (ZW)"},                        
                    ];
            return countryCode;
        },
    }     
}]);
